### ISSUE TITLE
数据结构 文章里有两处编辑错误

### ISSUE THREAD

**Issue by qihb** [liuzhen153/play-algorithm-python#3]
1.访问方式-随机访问
时间复杂度恒为：O(n)[这里不是O(1)吗？]
2.和链表对比：
添加，删除这个两个对比错误。建议应该加上查询，添加，删除。
访问|查询|添加|删除
--|:--:|--:|--:
链表|慢|快|快
数组|快|慢|慢

**Comment by liuzhen153** [comment]
1. 数组访问的时间复杂度确实写错了，应是O(1)，感谢~
2.访问 = 查询，另外确实是对比写错了，感谢指正~
